# A->B->F->J
# A->C->G
# A->D->H
# A->E->I

task A: [:B,:C,:D, :E] do
     puts "task A action"
end

task B: :F do
     puts "task B action"
end

task C: :G do
     puts "task C action"
end

task D: [:H] do
     puts "task D action"
end

task E: :I do
     puts "task E action"
end

task F: :J do
     puts "task F action"
end

task :G  do
     puts "task G action"
end

task :H do
     puts "task H action"
end

task :I do
     puts "task I action"
end

task :J  do
     puts "task J action"
end

